### ISSUE TITLE
OpenGL error 0x0501 in D:\dev\engine-v5\cocos\renderer\backend\opengl\TextureGL.cpp cocos2d::backend::Texture2DGL::updateData 206

### ISSUE THREAD

**Issue by halx99** [c4games/engine-v5#51]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. 
2.

**Comment by weiwest** [comment]
I have the same problem

when use compressd texture, the stack is
    Texture2DGL::updateTextureDescriptor
    Texture2DGL::initWithZeros()
    updateData(data, _width, _height, 0);

the GL error 0x0501 happen

I‘ll fix later.

**Comment by halx99** [comment]
This issue caused by incorrect shader compile, create a new issue to track, compress renderformat mismatch problem.
